# 1. Configuración Básica y Prefijo
set-option -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Colores reales (True Color) - Movido arriba para evitar parpadeos
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc"

set -g mouse on
setw -g mode-keys vi

# 2. División de Paneles (Path actual)
bind v split-window -h -c "#{pane_current_path}"
bind d split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# 3. Redimensionar y Maximizar
bind -r H resize-pane -L 5
bind -r J resize-pane -D 6
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind m resize-pane -Z

# 4. Modo Copia (Estilo LazyVim)
bind-key -T copy-mode-vi v send-key -X begin-selection
bind-key -T copy-mode-vi y send-key -X copy-selection-and-cancel

# 5. Plugins (TPM)
set -g @plugin 'tmux-plugins/tpm' # Asegúrate de tener esta línea
set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @plugin 'christoomey/vim-tmux-navigator'

# 6. Configuración del Tema Kanagawa
set -g @kanagawa-theme 'dragon'
set -g @kanagawa-plugins "git cpu-usage ram-usage session" # Añadí 'session' para que veas el nombre
set -g @kanagawa-ignore-window-colors true

# 7. Navegación inteligente (Mantenlo tal cual)
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

# 8. Inicializar TPM (SIEMPRE AL FINAL)
run '~/.tmux/plugins/tpm/tpm'
